services:

# Auth-Backend

  auth-service-backend:
    build:
      context: ./auth-service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_auth

# Auth-Database-Configuration

  db_shopflow_auth:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: shopflow_auth
      MYSQL_ROOT_PASSWORD: shopflow_auth@12345
    ports:
      - "3306:3306"
    networks:
      - shopflow-network
    restart:  always

# Auth-Frontend

  auth-service-frontend:
    build:
      context: ./auth-service/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://54.251.154.110:8000
        VITE_FRONTEND_URL: http://54.251.154.110:5173
    container_name: auth-frontend
    ports:
      - "5173:80"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_auth

# Home-Backend

  home-service-backend:
    build:
      context: ./home-page-service/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_home

# Home-Database-Configuration

  db_shopflow_home:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: shopflow_home
      MYSQL_ROOT_PASSWORD: shopflow_home@12345
    ports:
      - "3307:3306"
    networks:
      - shopflow-network
    restart:  always

# Home-Frontend
  home-service-frontend:
    build:
      context: ./home-page-service/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://54.251.154.110:8001
        VITE_FRONTEND_URL: http://54.251.154.110:5174
    container_name: home-frontend
    ports:
      - "5174:80"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_home



networks:
  shopflow-network:
    driver: bridge