services:
  # Auth-Backend

  auth-service-backend:
    build:
      context: ./auth-service/
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=django-insecure-2-jwrm$v@8vx&o7=zaa+-62zme=7qjr@()(mgwj)7xw=7rw(bi
      - DEBUG=True
      - DB_NAME=shopflow_auth
      - DB_USER=root
      - DB_PASSWORD=shopflow_auth@12345
      - DB_HOST=db_shopflow_auth
      - DB_PORT=3306
      - FRONTEND_UR=http://54.251.154.110:5173/
      - CORS_ORIGIN=http://54.251.154.110:5173
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=onboarding@resend.dev
    ports:
      - "8000:8000"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_auth

  # Auth-Database-Configuration

  db_shopflow_auth:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: shopflow_auth
      MYSQL_ROOT_PASSWORD: shopflow_auth@12345
    ports:
      - "3306:3306"
    networks:
      - shopflow-network
    volumes:
      - auth_service_db:/var/lib/mysql
    restart: always

  # Auth-Frontend

  auth-service-frontend:
    build:
      context: ./auth-service/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://54.251.154.110:8000
        VITE_FRONTEND_URL: http://54.251.154.110:5173
        VITE_HOME_URL: http://54.251.154.110:5174
    container_name: auth-frontend
    ports:
      - "5173:80"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_auth

  # Home-Backend

  home-service-backend:
    build:
      context: ./home-page-service/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=django-insecure-w2152-(0qht_8c^#vilr$33l@a3q=dz%vpl36ew)@=a^f43&b0
      - DEBUG=True
      - DB_NAME=shopflow_home
      - DB_USER=root
      - DB_PASSWORD=shopflow_home@12345
      - DB_HOST=db_shopflow_home
      - DB_PORT=3306
      - FRONTEND_URL=http://54.251.154.110:5173
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=onboarding@resend.dev
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_home

  # Home-Database-Configuration

  db_shopflow_home:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: shopflow_home
      MYSQL_ROOT_PASSWORD: shopflow_home@12345
    ports:
      - "3307:3306"
    networks:
      - shopflow-network
    volumes:
      - home_service_db:/var/lib/mysql
    restart: always

  # Home-Frontend
  home-service-frontend:
    build:
      context: ./home-page-service/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://54.251.154.110:8001
        VITE_FRONTEND_URL: http://54.251.154.110:5174
    container_name: home-frontend
    ports:
      - "5174:80"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_home

volumes: 
  auth_service_db:
  home_service_db:

networks:
  shopflow-network:
    driver: bridge
