services:

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-backend
    ports:
      - "8000:8000"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_auth

  db_shopflow_auth:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: shopflow_auth
      MYSQL_ROOT_PASSWORD: nikhil@97
    ports:
      - "3306:3306"
    networks:
      - shopflow-network
    restart:  always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth-frontend
    ports:
      - "5174:80"
    networks:
      - shopflow-network
    restart: always
    depends_on:
      - db_shopflow_auth

networks:
  shopflow-network:
    driver: bridge