# Generated by Django 5.0.6 on 2026-08-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
