# Generated by Django 5.0.6 on 2026-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pendingregistration_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
